### ISSUE TITLE
OS Error while executing upload.py

### ISSUE THREAD

**Issue by rahulkoli7** [s3542413-joseph-johnson/sinsy-project#19]
$ python2.7 upload.py --spkr 4 --synalpha 0.55 --vibpower 1 --f0shift 0 here_comes_the_sun.xml output.wav
Traceback (most recent call last):
  File "upload.py", line 61, in <module>
    requestFromWebsite(args.infile, args.outfile, spkrlang, args.spkr, args.synalpha, args.vibpower, args.f0shift)
  File "upload.py", line 9, in requestFromWebsite
    htmlOutput = subprocess.check_output([ 'curl', '-v', '-F', 'LANG=jp', '-F', 'SPKR_LANG='+spkrlang, '-F', 'SPKR='+spkr, '-F', 'SYNALPHA='+synalpha, '-F', 'VIBPOWER='+vibpower, '-F', 'F0SHIFT='+f0shift, '-F', 'SYNSRC=@' + infile, 'http://sinsy.sp.nitech.ac.jp/index.php' ])
  File "/usr/local/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/local/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Also if you could tell me how to make the project work .

**Comment by aluit** [comment]
Hi rahulkoli7
Have you got that input file handy? I'll try it out on my installation. sinsy is a bit limited in what it will process.

**Comment by rahulkoli7** [comment]
I used the xml files already provided in the repository. It worked out in listParts.py and keepPart.py but when I try to use upload.py this error pops up. In the above error I am using "here_comes_the_sun.xml". 
When i serached online about this problem their it was written that it should have "shell=true"  but i tried and it didnt work. 
I suppose it is not interacting with the website.

**Comment by aluit** [comment]
Your command worked fine for me. You must be having trouble accessing the website from your machine. Maybe check that curl is working. The problem isn't sinsy or this project's code.

**Comment by rahulkoli7** [comment]
How can I get sinsy compatible xml files to run. Can you somehow send me the xml file which works for you.

**Comment by arthurchoung** [comment]
My guess is that you don't have curl installed.

I think the error message has nothing to do with xml files.

**Comment by rahulkoli7** [comment]
It didn't had curl installed now it is running properly. Thank you so much for the help.
